const dummyText = ['Macaroon oat cake topping chocolate bar oat cake oat cake. Dragée lemon drops sweet chocolate jelly cake caramels. Lemon drops chocolate candy bear claw ice cream cheesecake. Liquorice cake marshmallow candy canes gummi bears. Cake tiramisu danish wafer donut pudding brownie shortbread. Sweet dragée cake cupcake chocolate candy canes. Gummi bears jelly toffee pie sesame snaps caramels toffee. Dragée tiramisu topping cookie cheesecake cake tootsie roll. Pie caramels lemon drops candy tootsie roll pastry donut jelly. Marzipan toffee bear claw ice cream jelly-o carrot cake caramels carrot cake. Candy jujubes liquorice danish fruitcake cheesecake gummies. Soufflé sweet roll powder fruitcake cotton candy jelly tart shortbread.' , 'Jelly-o cotton candy bonbon sweet roll jujubes gingerbread tootsie roll. Fruitcake lollipop bear claw donut cotton candy. Lollipop croissant pudding toffee oat cake sesame snaps cookie ice cream jelly beans. Halvah jelly beans cake bear claw brownie oat cake. Cotton candy croissant bear claw cotton candy marzipan jelly marshmallow. Gummies pastry pie cake bear claw icing jujubes lemon drops sweet roll. Lemon drops lemon drops pudding cake cake carrot cake cheesecake. Halvah pie soufflé pudding pie gingerbread. Cake croissant brownie bear claw croissant pudding caramels jelly-o powder. Cupcake icing marzipan tiramisu toffee topping jelly-o marshmallow. Candy canes pastry liquorice croissant chocolate bar wafer bear claw lollipop tart. Cheesecake topping macaroon dessert jelly beans marzipan. Lollipop caramels pastry cake cake oat cake candy pastry dragée.' , 'Chocolate bar halvah jelly beans ice cream croissant powder. Tart chocolate bar pudding candy canes dragée candy canes. Cookie croissant jelly-o dragée macaroon cake topping tootsie roll. Jelly beans pudding oat cake macaroon marzipan. Apple pie ice cream oat cake jelly sweet roll chocolate. Cookie jelly pastry lemon drops chocolate cake cupcake biscuit shortbread. Gingerbread croissant chocolate bar gingerbread chocolate bar. Sesame snaps liquorice gingerbread sweet roll croissant chupa chups donut caramels cupcake. Candy canes cheesecake danish marzipan liquorice. Dragée cotton candy dragée sugar plum topping pie halvah jelly powder. Cookie apple pie tiramisu marshmallow pudding jelly biscuit halvah. Carrot cake bear claw muffin dragée topping pie shortbread apple pie marshmallow. Ice cream wafer cheesecake marshmallow wafer jelly-o powder bear claw.' ,
 'Soufflé liquorice tart ice cream ice cream. Gummi bears sesame snaps ice cream chocolate cake candy canes jelly bonbon. Tiramisu cupcake jelly-o chupa chups donut. Cake tiramisu bonbon icing shortbread liquorice caramels gingerbread toffee. Marzipan jelly cookie cake sweet sesame snaps sweet roll shortbread candy canes. Oat cake donut topping cake wafer donut. Ice cream chupa chups cake powder soufflé toffee sweet muffin. Shortbread cookie toffee chupa chups caramels dessert bear claw sugar plum pudding. Lollipop shortbread sugar plum candy canes lemon drops oat cake soufflé. Wafer ice cream muffin cotton candy topping. Tootsie roll sweet roll powder chocolate cake sweet roll. Gingerbread carrot cake brownie cupcake tart dragée. Lemon drops cotton candy jujubes cupcake ice cream.' , 
'Ice cream soufflé croissant cotton candy apple pie lollipop brownie cake marshmallow. Sweet roll icing icing cheesecake dessert gummies ice cream. Cotton candy wafer topping chocolate bar chupa chups cookie candy canes sweet roll. Gummies marshmallow toffee icing cookie. Pie jujubes lemon drops candy canes tart croissant. Bear claw fruitcake topping soufflé candy canes dessert chocolate icing wafer. Jelly muffin biscuit sesame snaps fruitcake muffin pie candy sugar plum. Topping candy canes chocolate fruitcake marshmallow. Apple pie pastry marzipan chocolate bar jelly sugar plum cheesecake cheesecake. Halvah donut brownie marshmallow cotton candy. Chocolate bar cookie halvah gingerbread pudding candy lemon drops gummi bears. Pudding carrot cake sweet halvah sesame snaps carrot cake.' , 'Pudding soufflé gummies macaroon tiramisu lemon drops muffin oat cake. Marzipan jelly beans pie liquorice apple pie. Macaroon oat cake wafer croissant marzipan sweet chupa chups biscuit. Dessert ice cream candy canes ice cream candy canes. Bear claw cake soufflé fruitcake apple pie sugar plum cheesecake tart powder. Jelly ice cream brownie jujubes cake carrot cake cheesecake. Tart gingerbread icing tootsie roll sweet roll gingerbread. Donut tootsie roll pudding gingerbread halvah cupcake. Carrot cake chocolate bar brownie chocolate bar caramels caramels tiramisu. Wafer gummies bear claw sweet jelly-o wafer bear claw ice cream halvah. Chocolate cake lemon drops gummi bears jujubes jelly-o lollipop lemon drops cake sweet roll. Candy cake sugar plum liquorice tiramisu marzipan gummi bears.' ,
'Apple pie halvah jelly beans apple pie wafer ice cream donut jelly. Jelly cake gummies dessert sugar plum bear claw cookie croissant. Apple pie bonbon marzipan cake donut candy canes. Apple pie carrot cake bonbon cupcake macaroon lemon drops. Ice cream cheesecake cake gummi bears sugar plum. Lollipop pudding tart tiramisu tart dessert lemon drops lollipop. Marzipan bonbon halvah pastry dessert pastry cake cheesecake soufflé. Gingerbread gummi bears tiramisu sesame snaps cotton candy. Bonbon biscuit chocolate cake tootsie roll sweet jelly-o croissant. Chupa chups tootsie roll cookie caramels croissant halvah biscuit muffin. Jujubes gummi bears shortbread danish muffin. Wafer marshmallow cupcake pudding gingerbread candy tiramisu lollipop. Powder dragée carrot cake brownie ice cream cake soufflé.' ,
'Tart pudding bear claw gummi bears caramels ice cream tootsie roll tiramisu. Danish jelly-o biscuit sweet roll powder chupa chups. Soufflé croissant candy tootsie roll candy canes. Chocolate cake topping icing chocolate cupcake. Oat cake fruitcake cake jelly beans lemon drops jelly. Fruitcake candy canes lemon drops tart wafer jelly soufflé. Danish caramels jelly beans fruitcake topping bonbon. Cheesecake bonbon wafer gummies liquorice. Gummies cupcake liquorice gingerbread powder cake pudding shortbread. Biscuit chupa chups chocolate liquorice pastry tootsie roll bonbon gummies sugar plum. Lollipop toffee jelly-o jujubes marshmallow tart soufflé cookie chocolate cake. Tootsie roll oat cake oat cake bear claw caramels sesame snaps chupa chups gummies. Sweet gummi bears chocolate bonbon chupa chups dessert tootsie roll sugar plum.' ,
'Candy liquorice gingerbread bear claw cotton candy tiramisu liquorice. Liquorice marzipan icing cake cookie. Cookie cheesecake jelly beans jujubes pastry. Bonbon brownie cotton candy liquorice dessert marzipan jelly-o candy. Jelly donut pudding halvah brownie biscuit jujubes cotton candy ice cream. Fruitcake apple pie caramels danish bear claw jelly-o. Pie tart soufflé candy canes sugar plum. Liquorice dragée chocolate cake muffin jujubes croissant cotton candy sesame snaps cheesecake. Jelly pudding toffee pie lemon drops cotton candy sweet roll. Lollipop marzipan tiramisu jelly sweet roll brownie jelly beans ice cream. Apple pie shortbread lollipop croissant lemon drops biscuit chupa chups chupa chups. Pie liquorice biscuit dessert dragée pastry. Halvah chocolate bonbon jelly soufflé shortbread croissant jelly beans bonbon. Ice cream cupcake cheesecake marzipan tiramisu pudding powder biscuit marzipan.']
 

// selecting items 

const form = document.querySelector('#form');
const amount = document.querySelector('#amount');
const result = document.querySelector('#result')

//event listener

form.addEventListener('submit' , function(e) {
   e.preventDefault();

 const value = parseInt(amount.value);
const random = Math.floor(Math.random()*dummyText.length);

if(isNaN(value) || value <= 0 || value > 9) {
    result.innerHTML = `<p>${dummyText[random]}</p>`
} else {
    const slicedArray = dummyText.slice(0, value);
    const finalArray = slicedArray.map(function(singleDummy){
        return  `<p>${singleDummy}</p>`
    }).join('');

   result.innerHTML = finalArray;
}
})
